[project]
name = "dspy-gepa-interagent-comms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.3",
    "ipykernel>=7.1.0",
]
